### chat api

@baseUrl = http://localhost:6688

POST {{baseUrl}}/api/signup
Content-Type: application/json

{
    "email": "luxixi@yahoo.com",
    "password": "1234567",
    "fullname": "luxixi"
}

### sigin
# @name signin
POST {{baseUrl}}/api/signin
Content-Type: application/json

{
    "email": "luxixi@yahoo.com",
    "password": "1234567"
}

@token = {{signin.response.headers.authorization}}

### update chat

GET  {{baseUrl}}/api/chat
Authorization: {{token}}

### delete chat

DELETE {{baseUrl}}/api/chat/1
Authorization: {{token}}

### index

GET {{baseUrl}}
