### chat api

@baseUrl = http://localhost:6688

POST {{baseUrl}}/api/signup
Content-Type: application/json

{
    "email": "luxixi@yahoo.com",
    "password": "1234567",
    "fullname": "luxixi",
    "workspace": "Default"
}

### create user
POST {{baseUrl}}/api/signup
Content-Type: application/json

{
    "email": "luchujun@gmail.com",
    "password": "1234567",
    "fullname": "luchujun",
    "workspace": "Default"
}

### sigin
# @name signin
POST {{baseUrl}}/api/signin
Content-Type: application/json

{
    "email": "luxixi@yahoo.com",
    "password": "1234567"
}

@token = {{signin.response.headers.authorization}}

### get users
GET {{baseUrl}}/api/users/my_ws
Authorization: {{token}}

### update chat

GET  {{baseUrl}}/api/chats
Authorization: {{token}}

### create chat

POST {{baseUrl}}/api/chats
Authorization: {{token}}
Content-Type: application/json

{
    "name": "private chat",
    "members": [1,2],
    "public": false
}

### get chat by id
GET {{baseUrl}}/api/chats/1
Authorization: {{token}}

### delete chat

DELETE {{baseUrl}}/api/chats/1
Authorization: {{token}}

### get users in workspace
GET {{baseUrl}}/api/users/Default
Authorization: {{token}}

### index

GET {{baseUrl}}
