### chat api

POST  http://localhost:6688/api/signup
Content-Type: application/json

{
    "email": "luxixi@yahoo.com",
    "password": "1234567",
    "fullname": "luxixi"
}

### sign in

POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "luxixi@yahoo.com",
    "password": "1234567"
}

### update chat

PATCH http://localhost:6688/api/chat/1

### delete chat

DELETE http://localhost:6688/api/chat/1

### index

GET http://localhost:6688/
